export enum CallType {
    CHAT_PERSONAL_CODE = 'CHAT_PERSONAL_CODE',
    CHAT_STRANGER = 'CHAT_STRANGER',
    VIDEO_PERSONAL_CODE = 'VIDEO_PERSONAL_CODE',
    VIDEO_STRANGER = 'VIDEO_STRANGER'
  }
  
  export enum PreOfferAnswer {
    CALLEE_NOT_FOUND = 'CALLEE_NOT_FOUND',
    CALL_ACCEPTED = 'CALL_ACCEPTED',
    CALL_REJECTED = 'CALL_REJECTED',
    CALL_UNAVAILABLE = 'CALL_UNAVAILABLE'
  }
  
  export enum WebRTCSignaling {
    OFFER = 'OFFER',
    ANSWER = 'ANSWER',
    ICE_CANDIDATE = 'ICE_CANDIDATE'
  }
  
  export enum CallState {
    CALL_AVAILABLE = 'CALL_AVAILABLE',
    CALL_UNAVAILABLE = 'CALL_UNAVAILABLE',
    CALL_AVAILABLE_ONLY_CHAT = 'CALL_AVAILABLE_ONLY_CHAT'
  }
  